# Generated by Django 6.0.6 on 2026-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_slug", models.CharField(db_index=True, max_length=32)),
                ("order_id", models.CharField(db_index=True, max_length=128)),
                (
                    "amount",
                    models.BigIntegerField(help_text="مبلغ پایه\u200cی سفارش (ریال)"),
                ),
                (
                    "fee",
                    models.BigIntegerField(
                        default=0, help_text="کارمزد محاسبه\u200cشده (ریال)"
                    ),
                ),
                (
                    "amount_sent",
                    models.BigIntegerField(
                        default=0,
                        help_text="مبلغ واقعی ارسالی به بانک با کارمزد (ریال)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "در انتظار"),
                            ("redirect", "هدایت به بانک"),
                            ("returned", "بازگشت از بانک"),
                            ("complete", "تکمیل\u200cشده"),
                            ("cancelled", "لغو توسط کاربر"),
                            ("expire_token", "انقضای توکن درگاه"),
                            ("expire_verify", "انقضای تأیید"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=16,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="توکن بازگشتی از بانک در initiate",
                        max_length=255,
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="آدرس درگاه برای هدایت کاربر (پس از initiate)",
                        max_length=1000,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="شماره\u200cی پیگیری بانک پس از verify",
                        max_length=255,
                    ),
                ),
                ("card_number", models.CharField(blank=True, max_length=32)),
                ("callback_url", models.URLField(max_length=500)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["gateway_slug", "authority"],
                        name="iranian_pay_gateway_a3dd22_idx",
                    )
                ],
            },
        ),
    ]
